/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkerIndexRouteImport } from './routes/app.worker.index'
import { Route as AppVerifierIndexRouteImport } from './routes/app.verifier.index'
import { Route as AppAdvocateIndexRouteImport } from './routes/app.advocate.index'
import { Route as AppWorkerEarningsRouteImport } from './routes/app.worker.earnings'
import { Route as AppWorkerCommunityRouteImport } from './routes/app.worker.community'
import { Route as AppWorkerCertificateRouteImport } from './routes/app.worker.certificate'
import { Route as AppWorkerAnalyticsRouteImport } from './routes/app.worker.analytics'
import { Route as AppVerifierWorkersRouteImport } from './routes/app.verifier.workers'
import { Route as AppVerifierStatsRouteImport } from './routes/app.verifier.stats'
import { Route as AppAdvocateVulnerabilityRouteImport } from './routes/app.advocate.vulnerability'
import { Route as AppAdvocateComplaintsRouteImport } from './routes/app.advocate.complaints'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkerIndexRoute = AppWorkerIndexRouteImport.update({
  id: '/worker/',
  path: '/worker/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifierIndexRoute = AppVerifierIndexRouteImport.update({
  id: '/verifier/',
  path: '/verifier/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvocateIndexRoute = AppAdvocateIndexRouteImport.update({
  id: '/advocate/',
  path: '/advocate/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkerEarningsRoute = AppWorkerEarningsRouteImport.update({
  id: '/worker/earnings',
  path: '/worker/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkerCommunityRoute = AppWorkerCommunityRouteImport.update({
  id: '/worker/community',
  path: '/worker/community',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkerCertificateRoute = AppWorkerCertificateRouteImport.update({
  id: '/worker/certificate',
  path: '/worker/certificate',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkerAnalyticsRoute = AppWorkerAnalyticsRouteImport.update({
  id: '/worker/analytics',
  path: '/worker/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifierWorkersRoute = AppVerifierWorkersRouteImport.update({
  id: '/verifier/workers',
  path: '/verifier/workers',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifierStatsRoute = AppVerifierStatsRouteImport.update({
  id: '/verifier/stats',
  path: '/verifier/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvocateVulnerabilityRoute =
  AppAdvocateVulnerabilityRouteImport.update({
    id: '/advocate/vulnerability',
    path: '/advocate/vulnerability',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdvocateComplaintsRoute = AppAdvocateComplaintsRouteImport.update({
  id: '/advocate/complaints',
  path: '/advocate/complaints',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/advocate/complaints': typeof AppAdvocateComplaintsRoute
  '/app/advocate/vulnerability': typeof AppAdvocateVulnerabilityRoute
  '/app/verifier/stats': typeof AppVerifierStatsRoute
  '/app/verifier/workers': typeof AppVerifierWorkersRoute
  '/app/worker/analytics': typeof AppWorkerAnalyticsRoute
  '/app/worker/certificate': typeof AppWorkerCertificateRoute
  '/app/worker/community': typeof AppWorkerCommunityRoute
  '/app/worker/earnings': typeof AppWorkerEarningsRoute
  '/app/advocate/': typeof AppAdvocateIndexRoute
  '/app/verifier/': typeof AppVerifierIndexRoute
  '/app/worker/': typeof AppWorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/advocate/complaints': typeof AppAdvocateComplaintsRoute
  '/app/advocate/vulnerability': typeof AppAdvocateVulnerabilityRoute
  '/app/verifier/stats': typeof AppVerifierStatsRoute
  '/app/verifier/workers': typeof AppVerifierWorkersRoute
  '/app/worker/analytics': typeof AppWorkerAnalyticsRoute
  '/app/worker/certificate': typeof AppWorkerCertificateRoute
  '/app/worker/community': typeof AppWorkerCommunityRoute
  '/app/worker/earnings': typeof AppWorkerEarningsRoute
  '/app/advocate': typeof AppAdvocateIndexRoute
  '/app/verifier': typeof AppVerifierIndexRoute
  '/app/worker': typeof AppWorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/advocate/complaints': typeof AppAdvocateComplaintsRoute
  '/app/advocate/vulnerability': typeof AppAdvocateVulnerabilityRoute
  '/app/verifier/stats': typeof AppVerifierStatsRoute
  '/app/verifier/workers': typeof AppVerifierWorkersRoute
  '/app/worker/analytics': typeof AppWorkerAnalyticsRoute
  '/app/worker/certificate': typeof AppWorkerCertificateRoute
  '/app/worker/community': typeof AppWorkerCommunityRoute
  '/app/worker/earnings': typeof AppWorkerEarningsRoute
  '/app/advocate/': typeof AppAdvocateIndexRoute
  '/app/verifier/': typeof AppVerifierIndexRoute
  '/app/worker/': typeof AppWorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/check-email'
    | '/login'
    | '/verify-email'
    | '/app/advocate/complaints'
    | '/app/advocate/vulnerability'
    | '/app/verifier/stats'
    | '/app/verifier/workers'
    | '/app/worker/analytics'
    | '/app/worker/certificate'
    | '/app/worker/community'
    | '/app/worker/earnings'
    | '/app/advocate/'
    | '/app/verifier/'
    | '/app/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/check-email'
    | '/login'
    | '/verify-email'
    | '/app/advocate/complaints'
    | '/app/advocate/vulnerability'
    | '/app/verifier/stats'
    | '/app/verifier/workers'
    | '/app/worker/analytics'
    | '/app/worker/certificate'
    | '/app/worker/community'
    | '/app/worker/earnings'
    | '/app/advocate'
    | '/app/verifier'
    | '/app/worker'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/check-email'
    | '/login'
    | '/verify-email'
    | '/app/advocate/complaints'
    | '/app/advocate/vulnerability'
    | '/app/verifier/stats'
    | '/app/verifier/workers'
    | '/app/worker/analytics'
    | '/app/worker/certificate'
    | '/app/worker/community'
    | '/app/worker/earnings'
    | '/app/advocate/'
    | '/app/verifier/'
    | '/app/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  LoginRoute: typeof LoginRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/worker/': {
      id: '/app/worker/'
      path: '/worker'
      fullPath: '/app/worker/'
      preLoaderRoute: typeof AppWorkerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verifier/': {
      id: '/app/verifier/'
      path: '/verifier'
      fullPath: '/app/verifier/'
      preLoaderRoute: typeof AppVerifierIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advocate/': {
      id: '/app/advocate/'
      path: '/advocate'
      fullPath: '/app/advocate/'
      preLoaderRoute: typeof AppAdvocateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worker/earnings': {
      id: '/app/worker/earnings'
      path: '/worker/earnings'
      fullPath: '/app/worker/earnings'
      preLoaderRoute: typeof AppWorkerEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worker/community': {
      id: '/app/worker/community'
      path: '/worker/community'
      fullPath: '/app/worker/community'
      preLoaderRoute: typeof AppWorkerCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worker/certificate': {
      id: '/app/worker/certificate'
      path: '/worker/certificate'
      fullPath: '/app/worker/certificate'
      preLoaderRoute: typeof AppWorkerCertificateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worker/analytics': {
      id: '/app/worker/analytics'
      path: '/worker/analytics'
      fullPath: '/app/worker/analytics'
      preLoaderRoute: typeof AppWorkerAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verifier/workers': {
      id: '/app/verifier/workers'
      path: '/verifier/workers'
      fullPath: '/app/verifier/workers'
      preLoaderRoute: typeof AppVerifierWorkersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verifier/stats': {
      id: '/app/verifier/stats'
      path: '/verifier/stats'
      fullPath: '/app/verifier/stats'
      preLoaderRoute: typeof AppVerifierStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advocate/vulnerability': {
      id: '/app/advocate/vulnerability'
      path: '/advocate/vulnerability'
      fullPath: '/app/advocate/vulnerability'
      preLoaderRoute: typeof AppAdvocateVulnerabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advocate/complaints': {
      id: '/app/advocate/complaints'
      path: '/advocate/complaints'
      fullPath: '/app/advocate/complaints'
      preLoaderRoute: typeof AppAdvocateComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvocateComplaintsRoute: typeof AppAdvocateComplaintsRoute
  AppAdvocateVulnerabilityRoute: typeof AppAdvocateVulnerabilityRoute
  AppVerifierStatsRoute: typeof AppVerifierStatsRoute
  AppVerifierWorkersRoute: typeof AppVerifierWorkersRoute
  AppWorkerAnalyticsRoute: typeof AppWorkerAnalyticsRoute
  AppWorkerCertificateRoute: typeof AppWorkerCertificateRoute
  AppWorkerCommunityRoute: typeof AppWorkerCommunityRoute
  AppWorkerEarningsRoute: typeof AppWorkerEarningsRoute
  AppAdvocateIndexRoute: typeof AppAdvocateIndexRoute
  AppVerifierIndexRoute: typeof AppVerifierIndexRoute
  AppWorkerIndexRoute: typeof AppWorkerIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvocateComplaintsRoute: AppAdvocateComplaintsRoute,
  AppAdvocateVulnerabilityRoute: AppAdvocateVulnerabilityRoute,
  AppVerifierStatsRoute: AppVerifierStatsRoute,
  AppVerifierWorkersRoute: AppVerifierWorkersRoute,
  AppWorkerAnalyticsRoute: AppWorkerAnalyticsRoute,
  AppWorkerCertificateRoute: AppWorkerCertificateRoute,
  AppWorkerCommunityRoute: AppWorkerCommunityRoute,
  AppWorkerEarningsRoute: AppWorkerEarningsRoute,
  AppAdvocateIndexRoute: AppAdvocateIndexRoute,
  AppVerifierIndexRoute: AppVerifierIndexRoute,
  AppWorkerIndexRoute: AppWorkerIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  LoginRoute: LoginRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
